version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - SQS_MONITOR_INTERVAL_SECONDS=30
      - SQS_QUEUE_URLS=https://sqs.us-west-2.amazonaws.com/780213378361/gravity-qa-publisher-incoming-production,https://sqs.us-west-2.amazonaws.com/780213378361/nebula-incoming-urls-high,https://sqs.us-west-2.amazonaws.com/780213378361/nebula-incoming-urls-low,https://sqs.us-west-2.amazonaws.com/780213378361/nebula-incoming-urls-normal,https://sqs.us-west-2.amazonaws.com/780213378361/oversight-feature-processor-prod,https://sqs.us-west-2.amazonaws.com/780213378361/oversight-rts-processor-prod,https://sqs.us-west-2.amazonaws.com/780213378361/site-pipeline-processor-input-prod,https://sqs.us-west-2.amazonaws.com/780213378361/vic-mgmt-processor-prod
    ports:
      - 80:8080
